version: '3'
services:
  goweb:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "go run ./app/main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/GO
    ports: 
      - 8020:8020
    depends_on: 
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_database
      TZ: 'Asia/Tokyo'
    volumes: 
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/logs:/var/log/mysql
    ports: 
      - 3326:3306